feat(validation): Add support for validating an API Blueprint
apiaryio/drafter-npm pull request #6
Opened 2016-10-20 12:39 UTC by kylef

This pull request adds a new validation API which allows you to validate an API Blueprint without serialising the complete API Blueprint.

Dependencies:

- [ ] https://github.com/apiaryio/protagonist/pull/170
- [ ] drafter.js

2016-10-20 13:02 UTC, pksunkara requested changes

2016-10-20 13:02 UTC, pksunkara commented on lib/drafter.js
> +    validate: validate,
`protagonist.validate`. Similarly below.

2016-10-20 13:23 UTC, kylef commented on lib/drafter.js
> +    validate: validate,
Ah, I had that originally. I wrote some stub validate functions to test my tests. Forgot to restore this back before committing. Updated.

2016-10-20 13:56 UTC, pksunkara commented
Do you want to add a test for blueprint with error?

2016-10-20 23:41 UTC, kylef commented
Yes, I'll add one.

2016-10-31 15:45 UTC, pksunkara approved these changes

2016-10-31 16:21 UTC, merged